server:
  port: 8000

# 配置数据源信息
spring:
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动
    url: jdbc:mysql://47.100.205.157:3306/login?useUnicode=true&characterEncoding=UTF-8&autoReconnect
    username: root
    password: 8zHSSrBhXZQKqb1BfCtw8Q==
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP # 连接池名字
      max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: SELECT 1

# mybatis 配置

mybatis:
  type-aliases-package: com.zouchaoqun.login.pojo # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml  # mapper映射文件 classpath就是所有的resources文件下
  #监测每一次调用数据库的sql语句在控制台打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl